### ISSUE TITLE
setting vehicle type to "debris" caused a lot of problems.

### ISSUE THREAD

**Issue by westlakem** [KSP-RO/RP-1#2005]
I noticed I wasn't getting any science from any of my satellites. I went back and realized I hadn't separated my transfer stage from the science core.  That's when I saw this.
![image](https://github.com/KSP-RO/RP-1/assets/4505074/fae6900a-57fe-46dc-b855-647e63e2a04f)

once I renamed it and set it back to "probe" it went back to normal
![image](https://github.com/KSP-RO/RP-1/assets/4505074/8ec183a6-0705-4b57-81f2-53136127beb2)

I also cannot trigger stage separation on the vehicle anymore.  Here is a link to the save file https://drive.google.com/file/d/10nbkHwYclKA-l3MV4htyBs8Dgqmaca9g/view?usp=sharing

**Comment by pap1723** [comment]
This is intended behavior with Contract Configurator and Kerbalism. If something is marked Debris, you are essentially telling the game to forget about it. Otherwise the system would get bogged down looking at every single piece of actual debris in orbit to try to complete contracts and calculate for Kerbalism.
