### ISSUE TITLE
Mission Control Center not updating with unloaded vehicle

### ISSUE THREAD

**Issue by westlakem** [KSP-RO/RP-1#2008]
I have a vessel orbiting the moon that I'm just waiting on science to be delivered from in order to complete the mission.
![image](https://github.com/KSP-RO/RP-1/assets/4505074/83eec810-356f-4b1d-a2f1-643017c4b6f0)
Yet when I go back into the mission control building, it's not linking the vehicle's orbit to the mission report.
![image](https://github.com/KSP-RO/RP-1/assets/4505074/dd1fcc9b-0c6d-4983-a12b-90e54f2b1233)

Also is there a way to know when enough science has been transmitted that it'll mark the last part complete?  I warped forward a week and it still hadn't marked it complete even though it's currently transmitting data.
![image](https://github.com/KSP-RO/RP-1/assets/4505074/60cec0c7-5125-4956-9a29-596c48e6a641)

**Comment by bofhgr** [comment]
Your probe will try to send all of the data it has gathered from experiments at the same time, without prioritizing. The limit is the transmission rate that you can see if you hover on the icon that displays signal quality. You can then estimate how much time it will take to transmit everything to KSC. In your example picture above, because there is very little bandwidth, only the Cosmic Ray Science is being currently transmitted.

To get done with your contract faster, you can do the following:

Click on the >> next to each experiment's data to pause sending that data back to KSC. Pick up an experiment with very small run time like temperature or telemetry, barometer etc and only click to send their data to the KSC. From your example above, probably the Cosmic Ray Science is the fastest to complete it's run time, so you should disable everything else until all the data is transmitted. You should have that contract completed in a few minutes, and then you can come back here and re-enable all the ">>" data transmission for the rest of the experiments.

**Comment by westlakem** [comment]
It never read it as in orbit, even though the mission tracker showed it was.  Had to cheat it complete

**Comment by siimav** [comment]
I don't believe the parameters are supposed to update at all when viewed inside Mission Control facility.
As for the collect science parameter - it's changed now in #2083
