### ISSUE TITLE
Unlocking parts with the launch button prompt debits funds instead of credits

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RP-1#2029]
I'll try to get a repro on a different part, but that's what says in the title: 
I clicked launch on a rocket that had one part still locked. It prompted me to unlock it for 0 funds using 1000 in credit, and I still got charged the 1000 funds. In this case, the construction didn't happen because I didn't have enough funds after losing the 1000.

**Comment by Test-Account-KSP** [comment]
I can confirm, it happened to me too so I make sure to unlock parts before clicking the go button.
Additionally, unlocking a part from the R&D center made it disappear from parts choosing list in the VAB.  It only appeared with experimental parts on (but then it could be used normally).

**Comment by leudaimon** [comment]
Can you repro? I tried to repro on a different part in the exact same conditions and it didn't work

**Comment by Test-Account-KSP** [comment]
Reproduced as follows: 
- start a new career game
- research post-war avionics, build a sounding rocket LC
- building a rocket with a small bio capsule using the Launch button subtracts 1000+ funds

![screenshot16](https://github.com/KSP-RO/RP-1/assets/110846612/241498e2-a6c1-405c-9e6f-58d32dfa0fda)
![screenshot17](https://github.com/KSP-RO/RP-1/assets/110846612/86046850-50a7-4dba-acbf-708bb6259c56)

**Comment by Clayell** [comment]
I've had this problem as well and documented it on the discord, but I'll put the images here as well.
https://cdn.discordapp.com/attachments/620690446540341261/1120088977484021801/image.png
https://cdn.discordapp.com/attachments/620690446540341261/1120088978121568306/image.png

Reproduction:
> put advanced biological capsule on vessel (but dont unlock it) and have over 1000 in credit
tool vessel
hit the "launch" button to try to start building it
get hit with the "there are parts you have not unlocked button"
"unlock" the part
funds get taken away instead of credits
