### ISSUE TITLE
Lunar Orbiter and Lunar Impactor missions should not be mutually exclusive

### ISSUE THREAD

**Issue by Test-Account-KSP** [KSP-RO/RP-1#2037]
As the title says.  Why can't I accept both and complete both in one launch?  Is it done specifically to punish efficient design?

**Comment by hallucinogender** [comment]
The impactor and orbiter contracts should, in fact, be mutually exclusive.

A lunar impactor probe requires no maneuvers outside of low Earth orbit; the impactor **does not enter orbit of the Moon** before it impacts the surface. It is essentially a flyby, but with a somewhat more precise trajectory requirement due to the need to _hit_ the Moon rather than just barely _miss_ it.

An orbiter strictly requires an additional maneuver (unless you are using Principia to do a ballistic capture, but that takes so long that you'd need a _lot_ of mass dedicated just to power generation or to batteries, which is very mass-inefficient in the early game). This means that the spacecraft must have the ability to point in the right direction _at_ the Moon - or it must have a carefully-calculated trajectory and clever design which allows it to be spin-stabilized in low Earth orbit _and_ still accomplish an orbital insertion burn at the Moon.

If you were to combine an orbiter and an impactor into one mission, not only would you have the difficulty of reaching lunar orbit with a _higher_ mass than you would otherwise require, but you _also_ have to include propellant and engines for an additional de-orbit maneuver.

While it is hypothetically possible to combine the two types of mission, the payload margins of early lunar-capable launch vehicles do not reasonably allow for it. Additionally, it would not be worthwhile to develop a rocket capable of sending a joint orbiter-impactor mission early on. The data gathered by a lunar impactor mission is (at least for early impactors) collected by pointing telescopes on Earth towards the Moon. To gather similar data with an orbiter, you'd need to send a decent camera to lunar orbit, and while this _is_ possible, you'd be much better off launching two existing rockets and synchronizing trajectories than inventing a new expensive rocket for the sake of doing everything in one launch.

**Comment by Test-Account-KSP** [comment]
Sorry, but you don't know what you writing about.
All I need to do is separate a spin-stabilized orbiter after TLI in the correct orientation, then adjust the trajectory of the TLI stage so that it crashes into the moon.

**Comment by Test-Account-KSP** [comment]
Just in case, I have done it, so please don't tell it's impossible for this or that reason.

**Comment by hallucinogender** [comment]
Here are the reasons, in short, that you do not combine an early lunar orbiter and lunar impactor mission on the same spacecraft:

- The objective of a lunar orbiter is to gather scientific data over a long duration. If the orbiter and impactor are the same spacecraft, then you have to crash the orbiter into the Moon _early_, which means that your very expensive science spacecraft cannot gather as much scientific data as it would otherwise be capable of.
- The objective of a lunar impactor is to generate an impact on the lunar surface which can be observed by telescopes on Earth, in order to study the physical characteristics of the surface of the Moon. An impactor mission is sent on a direct impact trajectory from low Earth orbit, there is generally no orbital insertion burn at the Moon.
- If you combine these two missions together into one spacecraft, regardless of whether the orbiter and impactor are separate vehicles, it will be far too massive for most early lunar-capable launch vehicles. You will not fit a _useful_ scientific orbiter payload _and_ an impactor on the same Thor-Able (or similar).
- Most importantly from a game balance perspective, if you take a spacecraft on a lunar flyby trajectory, do an orbital insertion burn, and continue that orbital insertion burn until the trajectory is now an impact trajectory, the game will think that you have orbited the Moon. In reality, however, the point of orbiting the moon isn't to say "for a few seconds during this engine burn, my predicted trajectory was an orbit". The point is to place a spacecraft into lunar orbit that is capable of collecting useful scientific data over a longer period of time than can be accomplished with a flyby. You do not have enough mass budget to also include an impactor on a mission whose objective is orbital science, unless you have massively overbuilt your launch vehicle. RP-1 should not encourage massively overbuilding launch vehicles, therefore these contracts should not be able to be merged.

**Comment by Test-Account-KSP** [comment]
Impressive

**Comment by LuneoLucy** [comment]
> 

I am pretty sure test account is talking about two seperate crafts that would share TLI and then split up

**Comment by Test-Account-KSP** [comment]
Yes, it separates in two craft, one of which is an unguided spin-stabilized orbiter and the other is a spent TLI stage. _Massively overbuilt_ by adding an extra science core and a decoupler, the monstrosity hardly fits on a 65t pad and completes the contracts by a _technicality_ of meeting all contract requirements. What a horror.

![image](https://github.com/KSP-RO/RP-1/assets/110846612/de29cbb4-40fe-4ab9-bd96-54413fe1b0e4)

**Comment by NathanKell** [comment]
This isn't a "is it possible to do" decision. This is a gameplay decision, in the same way we no longer let you double-dip on 3000km downrange.
