### ISSUE TITLE
Make a system for pad ignition failures to force some recovery/refresh times

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-1#2047]
Per my discussion with NK on stream, he'd like to add this to make pad ignition failures have a penalty, but not a drastic one.

**Comment by hallucinogender** [comment]
Look through the settings and find the one that refers to "pre-launch ignition failures".

**Comment by NathanKell** [comment]
Yes, hence "make pad ignition failures...", i.e. the ones the already exist. The point is on RP-1's side, to make suffering one mean you have to do some minor fixing (a day's delay, say, on a big vessel) without requiring a complete recovery/rollback/etc.

**Comment by FNGRenegade** [comment]
To be honest for me pad failures are already a positive instead of a negative. Yes the scene transitions are annoying however every time an engine fails on the pad it costs me 4-12 days depending on the recovery/rollout times but also ends me up with 1000du of data. Which means engines are less likely to fail in air which usually causes a total mission failure and is much more costly both in time spend and credits. I actually found myself hoping for pad failures when bringing in new engines and my LR89 booster LR105 rocket even started off with 3 pad failures in a row getting me to 2k du for the LR 89s and 1k du for the LR105 in 30 days. If any of those failures happened in air I'd most likely be looking at less data and a bigger recovery time/price.

**Comment by lpgagnon** [comment]
> but also ends me up with 1000du of data

this is going away: https://github.com/KSP-RO/TestFlight/issues/278

**Comment by NathanKell** [comment]
No, the du from ignition failure is not going away. That issue is about making test stands and running engines so far past their rated burn time that they fail--you don't get du from running them normally, but you do get that failure du. And since you can rinse-and-repeat recover them, you can easily max your data.

I should go clarify that other issue.

**Comment by NathanKell** [comment]
@FNGRenegade that's a good point, should probably cut the du output at the same time as making the fixing very quick (say 1 day for craft that takes a week to rollout)?

**Comment by marsh1832** [comment]
I also like pad failures. They add to the tension of engine failures, but without the huge cost of a failed rocket. For example, with an early multi engine rocket, it make take several attempts to get all the engines to light. When you finally get it and the thing launches, it’s a bit of rush, and at the same time, you’re on edge hoping there isn’t a flight failure. Although 1000 du might be a bit much for a pad failure, the fact you get something for your troubles doesn’t make it a huge inconvenience, and that each attempt increases the odds the next attempt will light properly.

**Comment by FNGRenegade** [comment]
@marsh1832 a very fair point and when launching things with a lot of engines indeed very important. Maybe the du max could be a function of the amount of engines trending towards 250 or 500du as to not penalize craft with loads of engines too much like a Saturn or in more extreme cases a N1.

**Comment by KEKKJ123** [comment]
I admit that this approach has to some extent disrupted the game balance. The benefits of engine testing can be reduced, but should not be prohibited.(or cheese)
If I don't want my rocket to fail, even if I turn off the rollback function, I can solve it by copying the file, it's obviously meaningless, so Engine testing has become an acceptable solution.

**Comment by siimav** [comment]
Implemented in #2327
