### ISSUE TITLE
Leader Retirements Do Not Respect Revert

### ISSUE THREAD

**Issue by LuuBluum** [KSP-RO/RP-1#2067]
If you happen to run a simulation long enough that a leader (or leaders) retire during the simulation, they remain retired even after reverting the simulation. Presumably, this happens for non-simulations as well.

Note that the revert does properly respect the days they have left until retirement and resets that to what it was. It just keeps permanently any retirements that happened, despite reverting.

This can be reproduced simply by taking a game with an assigned leader and running a simulation of some arbitrary craft. Max out the warp speed while it sits on the landing pad until you get an alert that the leader has retired. Revert to vehicle assembly. The leader will be gone.

**Comment by NathanKell** [comment]
@siimav this is due to the VAB not having correct UT, right? Retirement is stock code which just checks UT, so when you revert, you're in the VAB but the UT is somwhere in the distance, and the strategy updates. We probably can bandaid this by not running strategy updates in the VAB (prefixing to false), but it's a wider class of bug and we might consider just harmony-ing GetUniversalTime() to be smarter.

**Comment by siimav** [comment]
Oh yeah, could very well be that.
