### ISSUE TITLE
Orbital Flight, Three Crew has too tight eccentricity req with Principia

### ISSUE THREAD

**Issue by StonesmileGit** [KSP-RO/RP-1#2125]
Due to how the Osculating Orbit is perturbed over time when using principia, the current eccentricity requirement is too tight.
https://github.com/KSP-RO/RP-1/blob/d3aa5a7a05f753c152a42142476fa20d0d9b2dfe/GameData/RP-1/Contracts/Earth%20Crewed/OrbitalFlight3.cfg#L83

Options to fix the issue:
- Remove the requirement
- Increase the allowed eccentricity (to something like 0.01)
- Check for the wanted eccentricity for a small, but not instantaneous time period

**Comment by Clayell** [comment]
What's the apoapsis and periapsis that you got with this? Using orbital calculators it looks like if they're only ~40km within each other itll be fine, which I believe principia can't do in the duration of the contract

**Comment by NathanKell** [comment]
Running some numbers I'm very skeptical that 0.002 is actually too tight. @Clayell you think 40km of shift between Ap and Pe given a ~300km orbit over a week is _less_ than what occurs with Principia?

**Comment by Clayell** [comment]
> Running some numbers I'm very skeptical that 0.002 is actually too tight. @Clayell you think 40km of shift between Ap and Pe given a ~300km orbit over a week is _less_ than what occurs with Principia?

Ah, I wasn't aware that it was a week. I wonder how they managed it in real life, as satellites such as Tiros-1 are still in a .002 eccentricity orbit. (634x667) Anyway, I think putting it to .005 should be enough, as that what the weather contract requirement currently has it as. (.005 should probably be the min for eccentricity requirements on other contracts as well)

**Comment by TwistedGiraffe** [comment]
> I wonder how they managed it in real life, as satellites such as Tiros-1 are still in a .002 eccentricity orbit. (634x667)

It did not. In Principia, there are two kinds of orbit. There is the Osculating Orbit, determined solely from the instantaneous displacement and velocity vectors, and the Mean Orbit, the motion of a satellite over an entire orbit fitted to a conic section. 

Osculating orbits are affected by short-period (less than or equal to the orbital period) perturbations. For instance, a satellite would move slightly faster near the equator due to the earth's flattening, increasing its osculating semi-major axis. However, since the mean orbit is fitted using an entire orbit, it is unaffected by the short-period perturbations, only the long-period ones. It is, therefore, much more steady than the osculating orbit. In a 300 km LEO, osculating eccentricity can vary up to 0.02 over an orbit. However, since earth is very close to a perfect ball, the mean eccentricity hardly reaches 0.005 over three months. 

MJ and Contract Configurator see only the osculating orbit. Therefore, even if the satellite moves in almost perfect circles, values in the contracts must be lenient.

**Comment by Clayell** [comment]
Oh wow, thanks for teaching me something! Does this mean that the listed eccentricities of satellites online are the mean eccentricities and not the osculating eccentricities?
