### ISSUE TITLE
Re-launching a SPH (and probably VAB) recovered vessel keeps its conditions from when it was recovered

### ISSUE THREAD

**Issue by Clayell** [KSP-RO/RP-1#2152]
This is likely intended behavior, but it can get kind of annoying. For example, upon landing my rocketplane the landing gear is deployed and all stages are activated, but in the SPH the landing gear is not-deployed and there are 2 distinct stages. This means that I either need to "edit" the recovered vessel by re-selecting the SPH version, or that I need to manually bring it back to the SPH version before the air launch begins. (and this includes having to turn off every single rcs) It would be nice if the vessel state was that of the SPH, and not the recovered vehicle. (or if there was an option like this that could be toggled)

**Comment by NathanKell** [comment]
What do you mean "the SPH version"? When you recover a vessel, you get...that vessel. It has no link to any .craft files, how could it? Do you mean that things are different between when you click 'recover' in the flight scene, and when it loads after you click the 'edit' button? If not, then it is entirely working as designed (and the only way it can work) that the craft you get on recovery is exactly the craft you recovered.

**Comment by Clayell** [comment]
> What do you mean "the SPH version"? When you recover a vessel, you get...that vessel. It has no link to any .craft files, how could it? Do you mean that things are different between when you click 'recover' in the flight scene, and when it loads after you click the 'edit' button? If not, then it is entirely working as designed (and the only way it can work) that the craft you get on recovery is exactly the craft you recovered.

Yeah I suppose I didn't clarify. The SPH version is the original version directly after building/editing the thing. I had a feeling that this was intended, but I am asking if there could be an option to revert the recovered craft back to the original version while recovering it without having to edit it, perhaps in exchange for more time required to recover?

**Comment by NathanKell** [comment]
Original version of what? KSP just knows you hit recover on a vessel. That vessel is a collection of parts with states. There's no telling how that vessel originated--it could have been undocked from something, staged away most of itself, been created by a contract, whatever. 
Further, even if we were to add some system so you could link an inflight vessel to a craft file, if we automatically replaced the recovered craft with the craft file, you'd have quite an edit time penalty, because the engine(s) would get replaced by fresh engines, changing their buildpoints significantly.
