### ISSUE TITLE
Patch all things that list EC or EC/s to be Joules or Watts

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-1#2186]
Per our discussion on stream and the prior issue, might as well move to scientific notation everywhere rather than making players do the mental conversions

**Comment by RubenOllesch** [comment]
Just my 2 cents, I'm not a maintainer:

I would also like to see scientific units used wherever possible,
but I think there's a larger issue with that KSP in general doesn't even display units for resources nor their derivates (rate of consumption).
What I mean is that in all of KSP's UIs you just have a resource name and then a number, without any units.

You can of course easily change the display name of a resource, but because resource names != units, it looks just off:

![grafik](https://github.com/KSP-RO/RP-1/assets/42176443/0b84d04a-8bd0-4eea-b4d8-5caeb6cff4fa)

The best way would be to have the resource names unchanged (so still "Electric Charge") but add the unit to the number:

![grafik](https://github.com/KSP-RO/RP-1/assets/42176443/89abf6db-7896-4faa-89a7-91b112b0c737)
(Also see the Liter "L" for RealFuels)

I don't know if and how this would be possible to implement.
An easier alternative would be to add the unit to all resource names in brackets, like "ElectricCharge (kJ)" or "LiquidOxygen (L)", but that might look messier.

**Comment by NathanKell** [comment]
More limited scope: just did the rate -> W conversion. Trying to change all the places where _amounts_ are displayed, across both stock and Kerbalism (and any of the other mods too...) is a bit too much to bite off.

**Comment by NathanKell** [comment]
@RubenOllesch between Kerbalism 3.18 and [this](https://github.com/KSP-RO/RealismOverhaul/commit/e3719846f09a858928cad3eeb5807c78cb076774) and prior commits to RO, that is now the case. Stay tuned for the next RO release (this was partially implemented in https://github.com/KSP-RO/RealismOverhaul/releases/tag/v17.5.0.0 but the PAW and resource panel and partlist tooltip resources are in the next release).

**Comment by RubenOllesch** [comment]
I'm seriously impressed at what you guys consistently manage to do, and so quickly too!
Keep it up, but also get some rest, if you need it :-)
