### ISSUE TITLE
Leader Charlie Bossart overly advantageous as chief designer

### ISSUE THREAD

**Issue by peternewman89** [KSP-RO/RP-1#2252]
There might be a typo, unless it's intended that Charlie Bossart as Chief Designer provide a 100% boost to balloon tank integration (supposed to be 10% maybe). As it stands, an Atlas Centaur with balloon tanks for both stages on a pad with 471 active engineers and 94% efficiency takes 47 days to integrate, while a double-size Atlas Centaur with 810 active engineers and 92.3% efficiency takes 42 days.

**Comment by NathanKell** [comment]
And how long do they take without that leader? I would expect the total reduction in integration time to be on the order of 10%, and to achieve that the reduction in integration time of _the tank parts alone_ needs to be quite high.

**Comment by peternewman89** [comment]
Seems like, on checking that, having him in place makes a difference of ~7d/15% for a vessel where those are the vast majority of it, which seems, then, not to be quite as OP, guess it's more a consequence of the LC itself just producing faster than I expected. Thanks!

**Comment by NathanKell** [comment]
15% in this case is actually spot-on, since generally a leader gives 10% generally or 15% for a specialty. Thanks for checking!

And yeah, the thing to get used to with LCs is that what you need to look at is the _cost_ to integrate, rather than necessarily the time--time will _tend_ to grow the larger the vehicle is, but sometimes there's economy of scale where more of the vessel is 'simple' parts like tanks and fuel and less is 'complex' parts like engines/payload/etc that take a long time to integrate.
