### ISSUE TITLE
RD-100 requires post-war rocketry testing

### ISSUE THREAD

**Issue by Codelet** [KSP-RO/RP-1#2266]
RD-100 is now not available from the start. Is it intended?

**Comment by NathanKell** [comment]
I thought I patchnoted this? Intended.

**Comment by hallucinogender** [comment]
> Is it a 3.0 change? Can't see anything in release notes. A bit curious about the reasons behind, but at least it is not a bug. Thanks :)

Presumably it is to match with the XLR-41. With the previous configuration, a US-only playthrough would have to use the A4 to launch a V-2 derivative from the start node, while the Soviets could start out with their own engine. Now, both either have to pay the entry cost for both engines, _or_ launch smaller rockets until the first rocketry tech is researched.

**Comment by NathanKell** [comment]
The first flight of the RD-100 was late 1940s, equivalent to XASR-1, XLR41, XLR10, and other engines in the Postwar node, rather than WW2-vintage. It was a 3.0 change, it's just I thought I had shipped it with 2.13. Oops.

And yes, on the gameplay side it's as @hallucinogender says, there was some serious imbalance there.
