### ISSUE TITLE
Game breaking issue?

### ISSUE THREAD

**Issue by iwillruletheworld** [KSP-RO/RP-1#2291]
![image](https://github.com/KSP-RO/RP-1/assets/62358420/269546f7-0ba0-4c44-a324-1607da159575)

[KSP.log](https://github.com/KSP-RO/RP-1/files/13233376/KSP.log)
so i came back after a few weeks and updated everything booted up the game and got those so yeah
any help would be great

**Comment by NathanKell** [comment]
You have a number of incompatible mods, and quite a few mods that aren't included in the express install. I'm less surprised you have an issue now and more surprised you didn't before. Please follow the [Install Guide](https://github.com/KSP-RO/RP-1/wiki/RO-&-RP-1-Express-Installation-for-1.12.3) to create a working install.

**Comment by iwillruletheworld** [comment]
ok thank you

**Comment by iwillruletheworld** [comment]
hey, do you know what the specific mod that caused that issue is?

**Comment by NathanKell** [comment]
I can't say with certainty what caused this particular issue, but reading your log I can say the following mods aren't supported and cause varying levels of problem:
Achievements
AECS
SimpleBoiloff
GenericEnginePlumeScaleFixes
Kerbal Engineer
SpaceTuxLibrary
KerbalActuators
DeployableEngines

The following mods don't provide any benefit and can be removed:
BetterBurnTime
MagiCore
SpaceDust

The following mods probably work but are not part of the express install and I can't swear to them being compatible:
AlarmExtensions
DiazosLandingHeight
(and a few other misc ones that look even more likely to be ok)


All this looks like you tried to install RP-1 on top of an existing install, or used a modlist from somewhere, or just selected RP-1 and a bunch of other mods on CKAN, rather than following the install guide.
