### ISSUE TITLE
Edits to stored crafts complete instantly, but opening a second time and saving the edit properly puts it in the queue.

### ISSUE THREAD

**Issue by drobie22** [KSP-RO/RP-1#2357]
First "save edits" completes instantly. If I want it to show in the build queue properly I have to save edits again.

**Comment by rjhelms** [comment]
with the caveat that I know basically nothing about the RP-1 codebase, in `SaveShipEdits` should it maybe be checking `newShip.IsFinished` rather than `editableShip.IsFinished`? It seems to me like at that point in the code path, editableShip is the version before the edits were made (which would explain the 'need to save twice' behaviour:

https://github.com/KSP-RO/RP-1/blob/99d9f40e3975966bfdcba500e1d45c3a75705faf/Source/RP0/Utilities/KCTUtilities.cs#L480-L499
