### ISSUE TITLE
Trying to unlock a new comm tech level while editing a vehicle doesn't work

### ISSUE THREAD

**Issue by Clayell** [KSP-RO/RP-1#2408]
See video below:
https://youtu.be/faLrIdUkipY

**Comment by siimav** [comment]
No ksp.log

**Comment by Clayell** [comment]
Woops, sorry about that.
https://drive.google.com/file/d/1XWsBTmIhAfkB6Qm5QtwRDDuUVF6ohIDB/view?usp=sharing

**Comment by siimav** [comment]
So the issue there is that the upgrade costs more than you have funds. The query that checks whether the upgrade can be afforded is inside RA itself and doesn't know anything about unlock credit. However if you had the funds then it would actually use up unlock credit and take nothing from funds.
I think the fix is to change the `ResolveValidationError()` code such that it feeds current unlock credit in there. The change needs to be done into RP-1 and to all other mods that have integrated with this feature.
