### ISSUE TITLE
Automated repeated contracts

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-1#870]
So one thing that really stalls out RP1 is the repeated contracts.  They're boring, they're repetitive, and tbh I don't think even with a bunch of extra work through the contract system, they won't get a lot more interesting - there's only so much you can do with a sounding rocket or commercial sat contract. 

At the same time, there's big gaps in the game between being able to do certain things that can only really be filled currently by doing some of those contracts.

I think one thing we should look at adding is automated repeated contracts (not with KoS :) )

1. When a player complete one of the formerly-repeatable contract, the game stores the vessel name, how much it cost, including rollout costs, and (ideally, if possible) how reliable it is by evaluating the TF reliability of all stages.

2. Those values are stored and the game switches to repeating those contracts for you on a regular basis (say, monthly, for instance, or whatever seems appropriate).  You get the value of the contract - your costs.

3. The player will always have a 'redo' contract available that lets them set a new benchmark if they come up with a cheaper/more reliable design.  Redo contracts might be forced every X number of years, when Y# of total techs are unlocked, or when the player reaches their first new tech from Z era.  These could come with updated requirements as well - for instance, commercial Sat contracts are currently tuned to have heavier payloads with better rewards the more techs you've unlocked, and it would be nice to maintain that behaviour in some fashion.  

The rewards of the contracts could then be tuned more closely to the costs, so there's more benefit for coming up with an efficient design.

Overall could massively reduce the 'grind' involved in playing RP1 in a way where you're always trying to do a contract, rather than just letting time pass - we'd want to make it so you'll have periods where you can't actually do any contracts, till you tech up - but you're constantly getting a flow of cash to offset maintenance costs.   

We can't do this with the contract system though.  #1 in particular can't be done in CC, (I checked with nightingale) and it would be nice to integrate the cash flow from each of repeated contracts into the balance sheet UI from RP1 rather than just having contracts that automatically complete every month and add some funds.

Other balance fixes would need to follow on too.  Besides just tuning the contract values, we'd likely need to make build times longer (as there'd be less pressure on the VAB queue). 

Thoughts?

**Comment by pianojosh** [comment]
I think you'd have to "spend" (permanently) build points and a launch pad to make this work, and that way it's even tunable up to some maximum. So you basically permanently give up some number of build points and a launch pad of the appropriate level.

The reliability bit would be difficult. You'd need to know the burn times in addition to aggregating the underlying reliabilities. Also, you could build a stage that has engine-out capability, so a single failure might not actually doom the mission.

It's a cool idea, but I'm not sure there's enough in-game to synthesize all this together to make something workable.

**Comment by pap1723** [comment]
Isn't there a mod that does something like this? Routine Mission Manager
maybe?

**Comment by ec429** [comment]
Note that personally I don't mind doing dozens of commercial sat launches, and I'd rather that wasn't taken away.
The bigger problem imho is that the progression of those contracts doesn't pace too well; in particular after getting to the point where Second Gen Weather Sat is too small (as in, launching one every 10 days), you'd think you'd move on to Sun Synch Weather Sat so that you could do your cash-grinding in bigger lumps.  But no, the sun-synch weather sat contract is only a little bit more challenging and doesn't seem to pay any more than the second-gen one.

**Comment by pianojosh** [comment]
@ec429 100% in agreement there. The "mature" contracts definitely leave a lot to be desired. Definitely a 3rd and 4th generation set of contracts for both LEO, polar, and GEO, with much higher payload requirements, probably need to be added, so that you can grind for cash without so many repetitive launches.

**Comment by ec429** [comment]
@pianojosh I'm also planning to add a third track of navigational satellites (to culminate in the existing GPS/GLONASS contracts).  Why?  Because if you've got multiple build rates, it's annoying not knowing what the payload requirement on the next weather sat contract will be because you've already got one active; if you want to fill up your VAB with stacking sats you have to find out the maximum from the contract config and use that.
And it adds a bit of variety, I suppose.

**Comment by siimav** [comment]
PLC almost entirely eliminated repeatable contracts.
